= 计算机专业词汇表
:doctype: book
:encoding: utf-8
:lang: zh-cn
:toc: left
:toc-title: 导航目录
:toclevels: 4
:sectnums:
:sectanchors:

:hardbreaks:
:experimental:
:icons: font

== 词汇

version skew::
释义:版本偏差
来源: https://kubernetes.io/docs/setup/release/[kubernetes]

bare metal environments::
释义:裸机环境
来源: https://kubernetes.io/docs/setup/[kubernetes]

portable::
释义:可移植的
来源: https://kubernetes.io/docs/concepts/overview/[kubernetes]
例句:Kubernetes is a portable, extensible, open-source platform;

manipulate::
释义:操作
例句:The Kubernetes API lets you query and manipulate the state of objects in Kubernetes;

underutilized::
释义:利用不足

underlying infrastructure::
释义:基础架构

Agile application creation and deployment::
释义:敏捷的应用程序创建和部署

Dev and Ops separation of concerns::
释义:开发和运营关注点分离

decouple::
释义:解耦
例句:create application container images at build/release time rather than deployment time,
thereby decoupling applications from infrastructure.

OS-level::
释义:操作系统级别
metrics::
释义:指标
例句:Observability not only surfaces OS-level information and metrics,
but also application health and other signals.

failover::
释义:故障转移
例句:It takes care of scaling and failover for your application, provides deployment patterns, and more.

quorum::
释义:多数派

canary deployment::
释义:金丝雀部署
https://docs.gitlab.com/ee/user/project/canary_deployments.html
https://martinfowler.com/bliki/CanaryRelease.html
https://en.wiktionary.org/wiki/canary_in_a_coal_mine[危险的预兆: canary in a coal mine]

traffic::
释义:流量
If traffic to a container is high, Kubernetes is able to load balance
and distribute the network traffic so that the deployment is stable.

Storage orchestration::
释义:存储编排;
Kubernetes allows you to automatically mount a storage system of your choice,
such as local storages, public cloud providers, and more.

Automated rollouts and rollbacks::
释义:自动化部署和回滚;

Self-healing::
释义:自我修复
Kubernetes restarts containers that fail, replaces containers,
kills containers that don't respond to your user-defined health check,
and doesn't advertise them to clients until they are ready to serve.

Continuous Integration, Delivery, and Deployment (CI/CD)::
释义:持续集成,持续发布/部署;

SaaS (Software as a Service)::
PaaS (Platform as a Service)::

powerful, robust, resilient, and extensible::
释义:强大,健壮,灵活和可扩展
例句:This results in a system that is easier to use and more
powerful, robust, resilient, and extensible

fault-tolerance::
容错

high availability::
高可用

persistence store::
持久存储

Interface Definition Language (IDL)::
接口定义语言

dumb-server::
沉默的服务器
dumb-server is software that fully depends on a connection to a server or cloud service for its functionality.
Without a network connection, the software offers nothing useful.

OpenAPI Specification(OAS)::
开源api(application programming interface)规范;
http://spec.openapis.org/oas/v3.0.3

navgaite::
浏览
You will learn how to navigate the edX platform, complete assessments,
and contribute to course discussions!

monolith::
独块巨石 -> 单体应用

utilitiy[utilities]::
实用程序

patch::
补丁

binary-compatible::
二进制兼容

ram(Random access memory)::
随机存取存储器
radom 此处含义为任意
Random-access memory (RAM /ræm/) is a form of computer memory that can be read and changed in any order,
typically used to store working data and machine code.
A random-access memory device allows data items to be read or written in almost the same amount of time
irrespective of the physical location of data inside the memory.

initramfs::
The initial ram filesystem, required for booting, sometimes called initrd, not initramfs.

Power On Self Test::
开机自检

BIOS::
Basic Input/Output System

ROM::
Read-Only Memory

compatibility::
兼容性

cutting edge system::
尖端系统

unary adj. /ˈjuːnəri/::
一元的

screenshot::
屏幕截图

circumstance /ˈsɜːrkəmstæns/::
环境

Coordinated Universal Time(UTC)::
Coordinated Universal Time (or UTC) is the primary time standard by which the world regulates clocks and time.
It is within about 1 second of mean solar time at 0° longitude, and is not adjusted for daylight saving time.
It is effectively a successor to Greenwich Mean Time (GMT).
https://en.wikipedia.org/wiki/Coordinated_Universal_Time
UTC is similar to, but more accurate than, Greenwich Mean Time (GMT).

Network Time Protocol (NTP)::
NTP is intended to synchronize all participating computers to within a few milliseconds of Coordinated Universal Time (UTC)
https://en.wikipedia.org/wiki/Network_Time_Protocol

Virtual Private Networks (VPNs)::
虚拟专用网络
https://en.wikipedia.org/wiki/Virtual_private_network

geo-blocking::
geography-blocking 地域限制技术

wide area network (WAN)::
广域网

Dynamic Host Configuration Protocol (DHCP)::
动态主机配置协议

Medium access control::
媒体访问控制-mac(网卡)
https://en.wikipedia.org/wiki/Medium_access_control
https://en.wikipedia.org/wiki/OSI_model
The MAC address is a unique hexadecimal number of your network card.

SSL::
Secure Sockets Layer (SSL) is a standard security technology for establishing an encrypted link
between a server and a client—typically a web server (website) and a browser,
or a mail server and a mail client (e.g., Outlook).

Transport Layer Security (TLS)::
https://en.wikipedia.org/wiki/Transport_Layer_Security
Transport Layer Security (TLS), and its now-deprecated predecessor, Secure Sockets Layer (SSL),
are cryptographic protocols designed to provide communications security over a computer network

Advanced Package Tool (APT)::
高级打包工具
apt->dpkg->debian-family-linux

Red Hat Package Manager (RPM)::
yum->rpm->fedora-family-linux

Secure SHell (SSH)::
Once your session is started (either by logging into a text terminal or via a graphical terminal program),
you can also connect and log into remote systems by using Secure SHell (SSH).

extra exact extract(易混淆)

Teletype(tty)::
原指电传打印机 => 虚拟终端

CPU (central processing unit) cycles::
cpu周期

steal time(st)::
Steal time is the percentage of time a virtual CPU waits for a real CPU
while the hypervisor is servicing another virtual processor.
https://scoutapm.com/blog/understanding-cpu-steal-time-when-should-you-be-worried

swap space::
https://segmentfault.com/a/1190000008125116

Virtual (VIRT), physical (RES), and shared memory (SHR)::
虚拟内存,物理内存,共享内存

back up and compress data::
备份和压缩数据

network filesystem(nfs)::
网络文件系统
https://zhuanlan.zhihu.com/p/78114809

net segment::
192.168.1.0/24表示网段是192.168.1.0，子网掩码是24位，子网掩码为：255.255.255.0，